### ISSUE TITLE
Supprort array with multiple examples

### ISSUE THREAD

**Issue by triet-truong-tiki** [Roger13/SwagDefGen#8]
Currently, when passing a Json array, only the first element is chosen to be one example. 
With OpenAPI version 3.0.0. we can pass `example` array with type `array`. See example in the [docs](https://swagger.io/docs/specification/adding-examples/#arrays).

**Comment by LukasParke** [comment]
@Roger13 Is this something you are interested in implementing?
I would be happy to assist if so :)

**Comment by Roger13** [comment]
Hey @LukeHagar, this seems like a cool feature! If you feel like implementing it, go for it and I would happily review and approve it. Otherwise let me know and I can try to tackle it on my free time 🙌

**Comment by LukasParke** [comment]
I think the main thing here is to add support for the items in the array that are DIFFERENT, so the output spec would ideally include the full range of options, and then an example for each specific return type.

I'll think through this a little bit and take a look at the project, and see what I can contribute.

**Comment by LukasParke** [comment]
Just a note @Roger13, your code documentation is fantastic :)

**Comment by Roger13** [comment]
@triet-truong-tiki Support PR was just merged, let us know if it didn't solve your issue.
